const defaultState = { notes: [], books: [], tasks: [], files: [] };
const github = JSON.parse(localStorage.getItem("department-ai-github") || "null");
let state = { ...defaultState, ...JSON.parse(localStorage.getItem("department-ai-data") || "{}") };
let currentView = "overview";
let syncBusy = false;

const $ = (selector) => document.querySelector(selector);
const esc = (value = "") => String(value).replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[char]));
const formatDate = (date) => new Date(date).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" });
const saveLocal = () => localStorage.setItem("department-ai-data", JSON.stringify(state));
const allItems = () => [...state.notes.map((item) => ({ ...item, kind: "note" })), ...state.books.map((item) => ({ ...item, kind: "book" })), ...state.tasks.map((item) => ({ ...item, kind: "task" }))].sort((a, b) => new Date(b.updatedAt) - new Date(a.updatedAt));
const authUsers = () => JSON.parse(localStorage.getItem("department-ai-users") || "[]");
const getSession = () => JSON.parse(localStorage.getItem("department-ai-session") || "null");
async function passwordHash(password) { const bytes = new TextEncoder().encode(password); const digest = await crypto.subtle.digest("SHA-256", bytes); return Array.from(new Uint8Array(digest)).map((byte) => byte.toString(16).padStart(2, "0")).join(""); }
function showAuthError(id, message) { $(`#${id}`).textContent = message; }
function updateProfile(user) { if (!user) return; const initials = user.name.split(/\s+/).map((part) => part[0]).join("").slice(0, 2).toUpperCase(); $("#profile-avatar").textContent = initials; $(".top-avatar").textContent = initials; $("#profile-name").textContent = user.name; $("#profile-email").textContent = user.email; }
function showWorkspace(user) { $("#auth-screen").hidden = true; $(".app-shell").hidden = false; updateProfile(user); updateSyncUi(); render(); if (github) loadFromGithub(); }
function showAuth() { $("#auth-screen").hidden = false; $(".app-shell").hidden = true; }

function showToast(message, error = false) {
  const toast = document.createElement("div"); toast.className = `toast${error ? " error" : ""}`; toast.textContent = message; $("#toast-region").append(toast);
  setTimeout(() => toast.remove(), 3500);
}
function updateSyncUi() {
  const connected = Boolean(github);
  $("#sync-dot").classList.toggle("connected", connected);
  $("#sync-label").textContent = syncBusy ? "Syncing…" : connected ? `GitHub: ${github.owner}/${github.repo}` : "Local mode";
  $("#sync-detail").textContent = syncBusy ? "Saving changes" : connected ? `Branch: ${github.branch}` : "Connect GitHub to sync";
}
function render() {
  $("#breadcrumb").textContent = currentView === "overview" ? "Battle Ground" : currentView[0].toUpperCase() + currentView.slice(1);
  document.querySelectorAll(".nav-item[data-view]").forEach((button) => button.classList.toggle("active", button.dataset.view === currentView));
  $("#notes-count").textContent = state.notes.length; $("#books-count").textContent = state.books.length; $("#tasks-count").textContent = state.tasks.filter((task) => task.status !== "done").length; $("#files-count").textContent = state.files.length;
  const views = { overview: renderOverview, notes: () => renderCollection("notes"), books: () => renderCollection("books"), tasks: renderTasks, files: renderFiles };
  $("#app-content").innerHTML = views[currentView]();
  $("#app-content").querySelectorAll("[data-action]").forEach((element) => element.addEventListener("click", handleAction));
}
function renderOverview() {
  const recent = allItems().slice(0, 5);
  return `<div class="hero"><div><p class="eyebrow">AI One’s Platform</p><h1>Welcome to Battle Ground.</h1><p>Your command center for notes, books, tasks, and files. Plan boldly, capture everything, and keep moving.</p></div>${quickCreateMenu("New note")}</div>
    <div class="stats-grid"><div class="stat-card"><div><p>Total notes</p><h3>${state.notes.length}</h3><p>Ideas in your workspace</p></div><span class="stat-icon blue">▤</span></div><div class="stat-card"><div><p>Bookshelf</p><h3>${state.books.length}</h3><p>Books you are tracking</p></div><span class="stat-icon purple">▥</span></div><div class="stat-card"><div><p>Open tasks</p><h3>${state.tasks.filter((task) => task.status !== "done").length}</h3><p>Things worth doing</p></div><span class="stat-icon orange">✓</span></div></div>
    <div class="dashboard-grid"><div class="panel"><div class="panel-heading"><h2>Recently updated</h2><button class="button text" data-action="view-notes">View all</button></div>${recent.length ? recent.map(recentItem).join("") : `<div class="empty-state">Your workspace is ready. Create your first note.</div>`}</div><div class="panel"><div class="panel-heading"><h2>Task progress</h2><span>${state.tasks.filter((t) => t.status === "done").length}/${state.tasks.length} complete</span></div>${renderProgress()}</div></div>`;
}
function recentItem(item) { return `<div class="recent-item"><span class="item-badge ${item.kind}">${item.kind === "note" ? "▤" : item.kind === "book" ? "▥" : "✓"}</span><div><strong>${esc(item.title)}</strong><small>${item.kind[0].toUpperCase() + item.kind.slice(1)} · ${formatDate(item.updatedAt)}</small></div></div>`; }
function renderProgress() { const total = state.tasks.length || 1; const done = state.tasks.filter((task) => task.status === "done").length; return `<div style="height:9px;background:#eff1f6;border-radius:8px;margin:11px 0 20px"><div style="height:100%;width:${done / total * 100}%;background:linear-gradient(90deg,#5c6df5,#8c6ce8);border-radius:8px"></div></div><div class="recent-item"><span class="item-badge task">✓</span><div><strong>${done ? `${done} task${done > 1 ? "s" : ""} completed` : "Start with one small task"}</strong><small>${state.tasks.length ? "Keep your momentum going" : "Add a task from the to-do section"}</small></div></div>`; }
function renderCollection(kind) {
  const label = kind === "notes" ? "notes" : "books"; const icon = kind === "notes" ? "▤" : "▥"; const items = state[kind];
  return `<div class="section-title"><div><p class="eyebrow">${kind === "notes" ? "Your ideas" : "Reading list"}</p><h1>${kind === "notes" ? "Notes" : "Books"}</h1><p>${kind === "notes" ? "Keep your thoughts clear and easy to find." : "A personal library for what you want to learn next."}</p></div><div><input class="search" id="collection-search" placeholder="Search ${label}..." />${kind === "notes" ? `<button class="button primary" data-action="new-note">＋ Add note</button>` : `<button class="button primary" data-action="new-book">＋ Add book</button>`}</div></div><div class="collection-grid" id="collection-grid">${items.length ? items.map((item) => collectionCard(item, kind, icon)).join("") : `<div class="empty-state panel" style="grid-column:1/-1">Nothing here yet. Add your first ${kind.slice(0, -1)}.</div>`}</div>`;
}
function quickCreateMenu(label) {
  return `<div class="quick-create"><button class="button primary" data-action="toggle-quick-create">${label} <span class="menu-caret">⌄</span></button><div class="quick-menu" hidden><button data-action="new-note">▤ <span>Write a note</span><small>Capture an idea or thought</small></button><button data-action="new-book">▥ <span>Add a book</span><small>Track something you want to read</small></button><button data-action="upload-image">▧ <span>Upload image</span><small>Add a photo to your workspace</small></button><button data-action="upload">↥ <span>Upload file</span><small>PDF or image up to 10 MB</small></button></div></div>`;
}
function collectionCard(item, kind, icon) { return `<article class="collection-card" data-title="${esc(item.title.toLowerCase())}"><div class="card-top"><span class="item-badge ${kind === "notes" ? "note" : "book"}">${icon}</span><button class="card-menu" data-action="edit" data-kind="${kind}" data-id="${item.id}">•••</button></div><h3>${esc(item.title)}</h3><p>${esc(item.description)}</p><div class="card-footer"><span>${esc(item.category || (kind === "books" ? "Book" : "Uncategorized"))}</span><span>${formatDate(item.updatedAt)}</span></div>${kind === "notes" ? `<button class="download-note" data-action="download-note" data-id="${item.id}">↓ Download note</button>` : ""}</article>`; }
function renderTasks() {
  return `<div class="section-title"><div><p class="eyebrow">Stay on track</p><h1>To-do tasks</h1><p>Turn good intentions into visible progress.</p></div><button class="button primary" data-action="new-task">＋ Add task</button></div><div class="task-list">${state.tasks.length ? state.tasks.map((task) => `<div class="task-row"><button class="task-check ${task.status === "done" ? "checked" : ""}" data-action="toggle-task" data-id="${task.id}">${task.status === "done" ? "✓" : ""}</button><div><strong>${esc(task.title)}</strong><small>${esc(task.description || "No description")}</small></div><span class="tag ${task.status}">${task.status === "progress" ? "In progress" : task.status === "done" ? "Completed" : "To do"}</span><span class="task-date">${formatDate(task.updatedAt)}</span><button class="delete-link" data-action="delete" data-kind="tasks" data-id="${task.id}">×</button></div>`).join("") : `<div class="empty-state">No tasks yet. Add one to get started.</div>`}</div>`;
}
function renderFiles() {
  return `<div class="section-title"><div><p class="eyebrow">Workspace files</p><h1>Files</h1><p>Keep PDFs, photos, and reference material close to your work.</p></div><button class="button primary" data-action="upload">↥ Upload file</button></div><div class="file-grid">${state.files.length ? state.files.map(fileCard).join("") : `<div class="empty-state panel" style="grid-column:1/-1">No files yet. Upload a PDF or image to get started.</div>`}</div>`;
}
function fileCard(file) {
  const isImage = file.type.startsWith("image/");
  const preview = isImage && file.dataUrl ? `<img src="${file.dataUrl}" alt="" />` : `<span class="file-type">${file.extension.toUpperCase()}</span>`;
  const remoteUrl = github ? `https://github.com/${github.owner}/${github.repo}/blob/${github.branch}/uploads/${file.id}.${file.extension}?raw=1` : "#";
  const fileUrl = file.dataUrl || (github ? remoteUrl : "#");
  return `<article class="file-card"><div class="file-preview ${isImage ? "image-preview" : ""}">${preview}</div><div class="file-info"><strong title="${esc(file.name)}">${esc(file.name)}</strong><small>${esc(file.folder)} · ${formatBytes(file.size)}</small></div><a class="button secondary file-open" href="${fileUrl}" ${file.dataUrl ? `download="${esc(file.name)}"` : ""} target="_blank" rel="noopener">${isImage ? "View" : "Open"}</a></article>`;
}
function formatBytes(bytes) { if (bytes < 1024 * 1024) return `${Math.max(1, Math.round(bytes / 1024))} KB`; return `${(bytes / 1024 / 1024).toFixed(1)} MB`; }
function openEditor(kind, item = {}) {
  $("#editor-modal").hidden = false; $("#item-kind").value = kind; $("#item-id").value = item.id || ""; $("#item-title").value = item.title || ""; $("#item-description").value = item.description || ""; $("#item-category").value = item.category || ""; $("#item-status").value = item.status || "todo";
  $("#editor-eyebrow").textContent = item.id ? `Edit ${kind.slice(0, -1)}` : `New ${kind.slice(0, -1)}`; $("#editor-title").textContent = item.id ? `Edit your ${kind.slice(0, -1)}` : `Create a ${kind.slice(0, -1)}`; $("#description-label").firstChild.textContent = kind === "notes" ? "About this note" : "Description"; $("#description-label").querySelector("textarea").placeholder = kind === "notes" ? "Describe the key idea, context, or details..." : "Write something useful..."; $("#status-label").hidden = kind !== "tasks"; $("#category-label").hidden = kind === "tasks"; $("#description-label").querySelector("textarea").required = true; $("#item-title").focus();
}
function downloadNote(note) { if (!note) return; const content = `${note.title}\n${"=".repeat(note.title.length)}\n\n${note.description || ""}\n\nCategory: ${note.category || "Uncategorized"}\nUpdated: ${formatDate(note.updatedAt)}\n`; const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([content], { type: "text/plain;charset=utf-8" })); link.download = `${note.title.replace(/[\\/:*?"<>|]/g, "-") || "note"}.txt`; link.click(); URL.revokeObjectURL(link.href); showToast("Note downloaded."); }
function closeModals() { document.querySelectorAll(".modal-backdrop").forEach((modal) => { modal.hidden = true; }); }
async function handleAction(event) {
  const action = event.currentTarget.dataset.action;
  if (action === "new-note") openEditor("notes"); if (action === "new-notes") openEditor("notes"); if (action === "new-book") openEditor("books"); if (action === "new-books") openEditor("books"); if (action === "new-task") openEditor("tasks"); if (action === "upload") openUpload(); if (action === "upload-image") openUpload("image/*"); if (action === "download-note") downloadNote(state.notes.find((item) => item.id === event.currentTarget.dataset.id));
  if (action === "toggle-quick-create") { const menu = event.currentTarget.parentElement.querySelector(".quick-menu"); menu.hidden = !menu.hidden; }
  if (action === "view-notes") { currentView = "notes"; render(); }
  if (action === "edit") openEditor(event.currentTarget.dataset.kind, state[event.currentTarget.dataset.kind].find((item) => item.id === event.currentTarget.dataset.id));
  if (action === "toggle-task") { const task = state.tasks.find((item) => item.id === event.currentTarget.dataset.id); task.status = task.status === "done" ? "todo" : "done"; task.updatedAt = new Date().toISOString(); await persistItem("tasks", task); render(); }
  if (action === "delete") { const kind = event.currentTarget.dataset.kind; state[kind] = state[kind].filter((item) => item.id !== event.currentTarget.dataset.id); saveLocal(); render(); await deleteFromGithub(kind, event.currentTarget.dataset.id); }
}
async function persistItem(kind, item) {
  saveLocal(); render(); if (!github) { showToast("Saved locally. Connect GitHub to sync."); return; } syncBusy = true; updateSyncUi(); try { await githubPut(`${kind}/${item.id}.json`, item); showToast("Saved and synced to GitHub."); } catch (error) { showToast(error.message, true); } finally { syncBusy = false; updateSyncUi(); }
}
async function deleteFromGithub(kind, id) {
  if (!github) return; try { const file = await githubRequest(`/contents/${kind}/${id}.json?ref=${encodeURIComponent(github.branch)}`); await githubRequest(`/contents/${kind}/${id}.json`, "DELETE", { message: `Delete ${kind.slice(0, -1)} ${id}`, sha: file.sha, branch: github.branch }); showToast("Deleted and synced."); } catch (error) { showToast(`Local delete saved; GitHub delete failed: ${error.message}`, true); }
}
async function githubRequest(path, method = "GET", body) { const response = await fetch(`/api/github${path}`, { method, headers: { ...(body ? { "Content-Type": "application/json" } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) }); if (!response.ok) { const detail = await response.json().catch(() => ({})); const message = method === "PUT" && response.status === 404 ? "GitHub rejected the upload. Regenerate the token with repository Contents: Read and write permission, then update .env and restart the server." : detail.message || "GitHub request failed"; throw new Error(`${message} (${response.status})`); } return response.status === 204 ? null : response.json(); }
async function githubPut(path, value) { let sha; try { sha = (await githubRequest(`/contents/${path}?ref=${encodeURIComponent(github.branch)}`)).sha; } catch (error) { if (!error.message.includes("404")) throw error; } const content = btoa(unescape(encodeURIComponent(JSON.stringify(value, null, 2)))); return githubRequest(`/contents/${path}`, "PUT", { message: `Update ${path.split("/")[0]} item`, content, ...(sha ? { sha } : {}), branch: github.branch }); }
async function githubPutBase64(path, content, message) { let sha; try { sha = (await githubRequest(`/contents/${path}?ref=${encodeURIComponent(github.branch)}`)).sha; } catch (error) { if (!error.message.includes("(404)")) throw error; } try { const result = await githubRequest(`/contents/${path}`, "PUT", { message, content, ...(sha ? { sha } : {}), branch: github.branch }); if (!result?.content?.path) throw new Error("GitHub did not confirm the file upload."); return result; } catch (error) { if (error.message.includes("This repository is empty")) throw new Error("GitHub cannot upload until the repository has an initial commit. Create a README file in the repository, then reconnect GitHub."); throw error; } }
async function loadFromGithub() {
  if (!github) return; syncBusy = true; updateSyncUi(); try { for (const kind of ["notes", "books", "tasks"]) { let files; try { files = await githubRequest(`/contents/${kind}?ref=${encodeURIComponent(github.branch)}`); } catch (error) { if (error.message.includes("(404)")) continue; throw error; } if (!Array.isArray(files)) continue; const loaded = []; for (const file of files.filter((entry) => entry.name.endsWith(".json"))) { const encoded = await githubRequest(`/contents/${file.path}?ref=${encodeURIComponent(github.branch)}`); loaded.push(JSON.parse(decodeURIComponent(escape(atob(encoded.content.replace(/\n/g, "")))))); } state[kind] = loaded; } let uploadFiles = []; try { uploadFiles = await githubRequest(`/contents/uploads?ref=${encodeURIComponent(github.branch)}`); } catch (error) { if (!error.message.includes("(404)")) throw error; } if (Array.isArray(uploadFiles)) { const metadataFiles = uploadFiles.filter((file) => file.name.endsWith(".json")); state.files = []; for (const file of metadataFiles) { const encoded = await githubRequest(`/contents/${file.path}?ref=${encodeURIComponent(github.branch)}`); const metadata = JSON.parse(decodeURIComponent(escape(atob(encoded.content.replace(/\n/g, ""))))); state.files.push(metadata); } } saveLocal(); render(); showToast("Workspace refreshed from GitHub."); } catch (error) { showToast(`Could not refresh: ${error.message}`, true); } finally { syncBusy = false; updateSyncUi(); } }
$("#main-nav").addEventListener("click", (event) => { const button = event.target.closest("[data-view]"); if (button) { currentView = button.dataset.view; render(); $("#sidebar")?.classList.remove("open"); } });
$("#editor-form").addEventListener("submit", async (event) => { event.preventDefault(); const kind = $("#item-kind").value; const id = $("#item-id").value || `${Date.now()}-${Math.random().toString(36).slice(2, 7)}`; const existing = state[kind].find((item) => item.id === id); const item = { id, title: $("#item-title").value.trim(), description: $("#item-description").value.trim(), category: $("#item-category").value.trim(), status: kind === "tasks" ? $("#item-status").value : undefined, createdAt: existing?.createdAt || new Date().toISOString(), updatedAt: new Date().toISOString() }; if (kind !== "tasks") delete item.status; const index = state[kind].findIndex((entry) => entry.id === id); if (index >= 0) state[kind][index] = item; else state[kind].unshift(item); closeModals(); await persistItem(kind, item); });
$("#settings-form").addEventListener("submit", async (event) => { event.preventDefault(); const config = { owner: $("#github-owner").value.trim(), repo: $("#github-repo").value.trim(), branch: $("#github-branch").value.trim() || "main" }; try { const response = await fetch("/api/config"); if (!response.ok) throw new Error("Secure server is not running. Start it with npm start."); const serverConfig = await response.json(); if (serverConfig.owner !== config.owner || serverConfig.repo !== config.repo || serverConfig.branch !== config.branch) throw new Error("The repository settings must match the server .env configuration."); await githubRequest(""); localStorage.setItem("department-ai-github", JSON.stringify(config)); location.reload(); } catch (error) { showToast(error.message, true); } });
function openUpload(accept = ".pdf,image/*") { $("#upload-modal").hidden = false; $("#upload-form").reset(); $("#upload-file").accept = accept; $("#selected-file").textContent = "No file selected"; $("#upload-file").focus(); }
$("#upload-file").addEventListener("change", () => { const file = $("#upload-file").files[0]; $("#selected-file").textContent = file ? `${file.name} · ${formatBytes(file.size)}` : "No file selected"; });
$("#upload-form").addEventListener("submit", async (event) => { event.preventDefault(); const file = $("#upload-file").files[0]; if (!file) return; if (!github) { showToast("Connect GitHub in settings before uploading files.", true); return; } if (file.size > 10 * 1024 * 1024) { showToast("Files must be 10 MB or smaller.", true); return; } if (!(file.type === "application/pdf" || file.type.startsWith("image/"))) { showToast("Only PDF and image files are supported.", true); return; } const reader = new FileReader(); reader.onerror = () => showToast("The selected file could not be read.", true); reader.onload = async () => { const dataUrl = String(reader.result); const id = `${Date.now()}-${Math.random().toString(36).slice(2, 7)}`; const extension = file.name.includes(".") ? file.name.split(".").pop().toLowerCase() : "bin"; const item = { id, name: $("#upload-name").value.trim() || file.name, originalName: file.name, extension, type: file.type, size: file.size, folder: $("#upload-folder").value, dataUrl, createdAt: new Date().toISOString() }; syncBusy = true; updateSyncUi(); try { const content = dataUrl.split(",")[1]; if (!content) throw new Error("The file did not produce valid upload data."); await githubPutBase64(`uploads/${id}.${extension}`, content, `Upload ${file.name}`); await githubPut(`uploads/${id}.json`, { ...item, dataUrl: undefined }); state.files.unshift(item); saveLocal(); closeModals(); render(); showToast(`Uploaded to ${github.owner}/${github.repo}/uploads.`); } catch (error) { showToast(`GitHub upload failed: ${error.message}`, true); } finally { syncBusy = false; updateSyncUi(); } }; reader.readAsDataURL(file); });
document.querySelectorAll("[data-close-modal]").forEach((button) => button.addEventListener("click", closeModals)); $("#open-settings").addEventListener("click", () => { $("#settings-modal").hidden = false; if (github) { $("#github-owner").value = github.owner; $("#github-repo").value = github.repo; $("#github-branch").value = github.branch; } }); $("#refresh-data").addEventListener("click", loadFromGithub); $("#mobile-menu").addEventListener("click", () => $(".sidebar").classList.toggle("open")); $("#logout-button").addEventListener("click", () => { localStorage.removeItem("department-ai-session"); showAuth(); }); document.querySelectorAll("[data-auth-tab]").forEach((tab) => tab.addEventListener("click", () => { document.querySelectorAll(".auth-tab").forEach((item) => item.classList.remove("active")); tab.classList.add("active"); const register = tab.dataset.authTab === "register"; $("#login-form").hidden = register; $("#register-form").hidden = !register; })); $("#login-form").addEventListener("submit", async (event) => { event.preventDefault(); showAuthError("login-error", ""); const email = $("#login-email").value.trim().toLowerCase(); const password = await passwordHash($("#login-password").value); const user = authUsers().find((item) => item.email === email && item.password === password); if (!user) { showAuthError("login-error", "Email or password is incorrect."); return; } localStorage.setItem("department-ai-session", JSON.stringify({ email: user.email })); showWorkspace(user); }); $("#register-form").addEventListener("submit", async (event) => { event.preventDefault(); showAuthError("register-error", ""); const name = $("#register-name").value.trim(); const email = $("#register-email").value.trim().toLowerCase(); const password = $("#register-password").value; if (password !== $("#register-confirm").value) { showAuthError("register-error", "Passwords do not match."); return; } const users = authUsers(); if (users.some((item) => item.email === email)) { showAuthError("register-error", "An account with this email already exists."); return; } const user = { name, email, password: await passwordHash(password), createdAt: new Date().toISOString() }; users.push(user); localStorage.setItem("department-ai-users", JSON.stringify(users)); localStorage.setItem("department-ai-session", JSON.stringify({ email })); showWorkspace(user); }); document.addEventListener("input", (event) => { if (event.target.id === "collection-search") { const query = event.target.value.toLowerCase(); document.querySelectorAll(".collection-card").forEach((card) => { card.style.display = card.dataset.title.includes(query) ? "" : "none"; }); } });
const session = getSession(); const sessionUser = session && authUsers().find((user) => user.email === session.email); if (sessionUser) showWorkspace(sessionUser); else showAuth();
